name: gym_rats
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  kongelado_annotation:
    path: ./../flutter_packages_kugel/kongelado_annotation
  flutter_hooks: ^0.20.5
  get: ^4.6.6
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  fluentui_system_icons: ^1.1.263
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  toastification: ^2.3.0
  intl: ^0.19.0
  logger: ^2.4.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  isar_generator: ^3.1.0+1
  kongelado_generator:
    path: ./../flutter_packages_kugel/kongelado_generator
